### ISSUE TITLE
issue with PlotPCA & PlotPairs of Expression.py  script

### ISSUE THREAD

**Issue by csandorfr** [CGATOxford/cgat#115]
Hi

I have the following error when I use runExpression.py (same error with PlotPCA):

python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py               --method=summary               --design-tsv-file=design.tsv               --tags-tsv-file=feature_counts.dir/genesetexons.feature_counts.tsv.gz               --output-filename-pattern=designs.dir/design_vs_genesetexons.feature_counts_stats_               --log=designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log               > designs.dir/design_vs_genesetexons.feature_counts_stats.tsv
Traceback (most recent call last):
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 386, in <module>
    sys.exit(main(sys.argv))
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 334, in main
    filename_design=options.input_filename_design
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 2134, in outputTagSummary
    plotPairs()
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 695, in plotPairs
    log="xy")''')
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in pairs.default(countsTable, lower.panel = panel.pearson, pch = ".",  : 
  only one column in the argument to 'pairs'

My two input file are:

(cgat-venv)bash-4.1$ head design.tsv
THplus-NHDF1-R1.star    1       Ctr     0
THplus-OX119-R1.star    1       Ctr     0
THplus-AH016-R1.star    1       Ctr     0
THplus-JR036-R1.star    1       Case    0
THplus-MK144-R1.star    1       Case    0
THplus-MK002-R1.star    1       Case    0

(cgat-venv)bash-4.1$ zcat feature_counts.dir/genesetexons.feature_counts.tsv.gz | head
Geneid  THplus-AH016-R1.star   THplus-JR036-R1.star     THplus-MK002-R1.star    THplus-MK144-R1.star    THplus-NHDF1-R1.star    THplus-OX119-R1.star
ENSG00000223972 0      1       1  0     0   1
ENSG00000227232 54     30      30 32    14  14
ENSG00000243485 0      0       0  0     0   0
ENSG00000237613 0      0       0  0     0   0
ENSG00000268020 0      0       0  0     0   0
ENSG00000240361 6      0       0  0     0   0
ENSG00000186092 0      0       0  0     0   0
ENSG00000238009 0      0       0  7     0   0
ENSG00000239945 0      0       0  0     0   0

rpy2 & ggplot2 are installed and work

Cynthia

**Comment by MikeDMorgan** [comment]
Hi Cynthia,
It looks like your design matrix is mis-specified, there should be a numeric identifier that differentiates between cases and controls; they are all 0's at the moment.  See the documentation example in runExpression.py

**Comment by MikeDMorgan** [comment]
Hi Cynthia,
It's not reading in your counts data properly.  Expression.py uses the 'read.delim' function to read the tags file.  The default delimiter is 'tab' rather than any whitespace.  I'll change it to use the 'read.table', which takes any whitespace as the delimiter.  For now try using a tab-delimited tags file.
Thanks.
Mike

**Comment by csandorfr** [comment]
I used tab and not whitespace it doesn't work:

zcat feature_counts.dir/genesetexons.feature_counts.tsv.gz | head | od -c
0000000   G   e   n   e   i   d  \t   T   H   p   l   u   s   -   A   H
0000020   0   1   6   -   R   1   .   s   t   a   r  \t   T   H   p   l
0000040   u   s   -   J   R   0   3   6   -   R   1   .   s   t   a   r
0000060  \t   T   H   p   l   u   s   -   M   K   0   0   2   -   R   1
0000100   .   s   t   a   r  \t   T   H   p   l   u   s   -   M   K   1
0000120   4   4   -   R   1   .   s   t   a   r  \t   T   H   p   l   u
0000140   s   -   N   H   D   F   1   -   R   1   .   s   t   a   r  \t
0000160   T   H   p   l   u   s   -   O   X   1   1   9   -   R   1   .
0000200   s   t   a   r  \n   E   N   S   G   0   0   0   0   0   2   2
0000220   3   9   7   2  \t   0  \t   1  \t   1  \t   0  \t   0  \t   1
0000240  \n   E   N   S   G   0   0   0   0   0   2   2   7   2   3   2
0000260  \t   5   4  \t   3   0  \t   3   0  \t   3   2  \t   1   4  \t
0000300   1   4  \n   E   N   S   G   0   0   0   0   0   2   4   3   4
0000320   8   5  \t   0  \t   0  \t   0  \t   0  \t   0  \t   0  \n   E
0000340   N   S   G   0   0   0   0   0   2   3   7   6   1   3  \t   0
0000360  \t   0  \t   0  \t   0  \t   0  \t   0  \n   E   N   S   G   0
0000400   0   0   0   0   2   6   8   0   2   0  \t   0  \t   0  \t   0
0000420  \t   0  \t   0  \t   0  \n   E   N   S   G   0   0   0   0   0
0000440   2   4   0   3   6   1  \t   6  \t   0  \t   0  \t   0  \t   0
0000460  \t   0  \n   E   N   S   G   0   0   0   0   0   1   8   6   0
0000500   9   2  \t   0  \t   0  \t   0  \t   0  \t   0  \t   0  \n   E
0000520   N   S   G   0   0   0   0   0   2   3   8   0   0   9  \t   0
0000540  \t   0  \t   0  \t   7  \t   0  \t   0  \n   E   N   S   G   0
0000560   0   0   0   0   2   3   9   9   4   5  \t   0  \t   0  \t   0
0000600  \t   0  \t   0  \t   0  \n
0000607

**Comment by MikeDMorgan** [comment]
Okay, try putting the header row into the design file:
"track \t include \t group\t pair \n"

**Comment by csandorfr** [comment]
I added header
It is changes nothing:

head design.tsv 
track   include group  pair
THplus-NHDF1-R1.star   1       Ctr 0
THplus-OX119-R1.star   1       Ctr 0
THplus-AH016-R1.star   1       Ctr 0
THplus-JR036-R1.star   1       Case     0
THplus-MK144-R1.star   1       Case     0
THplus-MK002-R1.star   1       Case     0

 python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py               --method=summary               --design-tsv-file=design.tsv               --tags-tsv-file=feature_counts.dir/genesetexons.feature_counts.tsv.gz               --output-filename-pattern=designs.dir/design_vs_genesetexons.feature_counts_stats_               --log=designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log               > designs.dir/design_vs_genesetexons.feature_counts_stats.tsv
Traceback (most recent call last):
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 386, in <module>
    sys.exit(main(sys.argv))
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 334, in main
    filename_design=options.input_filename_design
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 2148, in outputTagSummary
    plotPCA(groups=False)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 747, in plotPCA
    R('''plot(p1)''')
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'

**Comment by AndreasHeger** [comment]
Hi Cynthia,

what does the logfile say?

Can you try setting "1" as pair (not "0")
I am not sure, but I am worried that "0" somewhere
might be interpreted as a False value and the
samples not being included.

Best

**Comment by csandorfr** [comment]
Hi Andreas,

I have same error:

head design.tsv 
track   include group  pair
THplus-NHDF1-R1.star   1       Ctr 1
THplus-OX119-R1.star   1       Ctr 1
THplus-AH016-R1.star   1       Ctr 1
THplus-JR036-R1.star   1       Case     1
THplus-MK144-R1.star   1       Case     1
THplus-MK002-R1.star   1       Case     1

(cgat-venv)bash-4.1$ python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py               --method=summary               --design-tsv-file=design.tsv               --tags-tsv-file=feature_counts.dir/genesetexons.feature_counts.tsv.gz               --output-filename-pattern=designs.dir/design_vs_genesetexons.feature_counts_stats_               --log=designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log               > designs.dir/design_vs_genesetexons.feature_counts_stats.tsv
Traceback (most recent call last):
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 386, in <module>
    sys.exit(main(sys.argv))
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 334, in main
    filename_design=options.input_filename_design
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 2148, in outputTagSummary
    plotPCA(groups=False)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 747, in plotPCA
    R('''plot(p1)''')
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'

It is not something with rpy2.

Thanks

Cynthia

**Comment by csandorfr** [comment]
I forget the log file

designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log

# output generated by /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py --method=summary --design-tsv-file=design.tsv --tags-tsv-file=feature_counts.dir/genesetexons.feature_counts.tsv.gz --output-filename-pattern=designs.dir/design_vs_genesetexons.feature_counts_stats_ --log=designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log
# job started at Fri Jan 30 16:29:31 2015 on fgu217.anat.ox.ac.uk -- b10c5145-6619-41b6-b94b-fc86e2a2e52a
# pid: 56565, system: Linux 2.6.32-504.3.3.el6.x86_64 #1 SMP Fri Dec 12 16:05:43 EST 2014 x86_64
# deseq_dispersion_method                 : pooled
# deseq_fit_type                          : parametric
# deseq_sharing_mode                      : maximum
# edger_dispersion                        : 0.4
# fdr                                     : 0.1
# filter_min_counts_per_row               : 1
# filter_min_counts_per_sample            : 10
# filter_percentile_rowsums               : 0
# input_filename_design                   : design.tsv
# input_filename_tags                     : feature_counts.dir/genesetexons.feature_counts.tsv.gz
# loglevel                                : 1
# method                                  : summary
# output_filename                         : <open file \'<stdout>\', mode \'w\' at 0x7f06dd893150>
# output_filename_pattern                 : designs.dir/design_vs_genesetexons.feature_counts_stats_
# output_force                            : False
# pseudo_counts                           : 0
# random_seed                             : None
# ref_group                               : None
# save_r_environment                      : None
# short_help                              : None
# spike_expression_bin_width              : 0.5
# spike_expression_max                    : 5.0
# spike_foldchange_bin_width              : 0.5
# spike_foldchange_max                    : 4.0
# spike_max_counts_per_bin                : 50
# stderr                                  : <open file \'<stderr>\', mode \'w\' at 0x7f06dd8931e0>
# stdin                                   : <open file \'<stdin>\', mode \'r\' at 0x7f06dd8930c0>
# stdlog                                  : <open file \'designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log\', mode \'a\' at 0x6828db0>
# stdout                                  : <open file \'<stdout>\', mode \'w\' at 0x7f06dd893150>
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
2015-01-30 16:29:31,896 INFO loading tag data from feature_counts.dir/genesetexons.feature_counts.tsv.gz
2015-01-30 16:29:31,896 INFO loading tag data from feature_counts.dir/genesetexons.feature_counts.tsv.gz

**Comment by AndreasHeger** [comment]
It should say something like this:

```
2014-11-28 11:37:13,360 INFO loading tag data from feature_counts.dir/refcoding.feature_counts.tsv.gz
2014-11-28 11:37:13,360 INFO loading tag data from feature_counts.dir/refcoding.feature_counts.tsv.gz
2014-11-28 11:37:14,044 INFO read data: 22865 observations for 24 samples
```
Basically, the R pairs function is complaining that it can't plot a scatter matrix with only a single column
of data. 

I still think there is a problem somewhere with the design matrix. I will add some more status messages
to help debugging.

**Comment by csandorfr** [comment]
Hi the output my log file seems now similar than you:

2015-02-03 17:01:59,861 INFO loading tag data from feature_counts.dir/genesetexons.feature_counts.tsv.gz
2015-02-03 17:01:59,861 INFO loading tag data from feature_counts.dir/genesetexons.feature_counts.tsv.gz
2015-02-03 17:02:00,899 INFO read data: 57773 observations for 6 samples
2015-02-03 17:02:00,909 WARNING missing samples from design file are ignored: ['N']
2015-02-03 17:02:00,925 INFO filtered data: 57773 observations for 6 samples
2015-02-03 17:02:02,250 INFO removed 26217 empty rows
2015-02-03 17:02:02,251 INFO trimmed data: 29175 observations for 6 samples
2015-02-03 17:02:02,609 INFO outputting maximum counts per window to designs.dir/design_vs_genesetexons.feature_counts_stats_max_counts.tsv.gz
2015-02-03 17:02:02,702 INFO removing rows with no counts in any sample
2015-02-03 17:02:02,789 INFO removed 0 empty rows
2015-02-03 17:02:02,790 INFO trimmed data: 29175 observations for 6 samples
2015-02-03 17:02:02,811 INFO outputting sample correlations table to designs.dir/design_vs_genesetexons.feature_counts_stats_correlation.tsv
2015-02-03 17:02:02,817 INFO outputting scatter plots to designs.dir/design_vs_genesetexons.feature_counts_stats_scatter.png
2015-02-03 17:02:06,906 INFO outputting correlation heatmap to designs.dir/design_vs_genesetexons.feature_counts_stats_heatmap.svg
2015-02-03 17:02:06,963 INFO outputting PCA plot to designs.dir/design_vs_genesetexons.feature_counts_stats_pca.svg

However I have this error:

python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py --method=summary --design-tsv-file=design.tsv --tags-tsv-file=feature_counts.dir/genesetexons.feature_counts.tsv.gz --output-filename-pattern=designs.dir/design_vs_genesetexons.feature_counts_stats_ --log=designs.dir/design_vs_genesetexons.feature_counts_stats.tsv.log > designs.dir/design_vs_genesetexons.feature_counts_stats.tsv
Traceback (most recent call last):
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 386, in <module>
    sys.exit(main(sys.argv))
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 334, in main
    filename_design=options.input_filename_design
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 2148, in outputTagSummary
    plotPCA(groups=False)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 747, in plotPCA
    R('''plot(p1)''')
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'

**Comment by AndreasHeger** [comment]
Thanks. Not sure what is wrong, but I will add code to catch this exception. It is currently in travis.

**Comment by AndreasHeger** [comment]
@csandorfr I have just added merged this - can you check out the latest version and retry?

**Comment by csandorfr** [comment]
I updated my version but when I try to rebuild my extension I have the following error

unning develop
running egg_info
writing requirements to CGAT.egg-info/requires.txt
writing CGAT.egg-info/PKG-INFO
writing top-level names to CGAT.egg-info/top_level.txt
writing dependency_links to CGAT.egg-info/dependency_links.txt
reading manifest file 'CGAT.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'CGAT.egg-info/SOURCES.txt'
running build_ext
skipping 'CGAT/Components/Components.cpp' Cython extension (up-to-date)
skipping 'CGAT/NCL/cnestedlist.c' Cython extension (up-to-date)
skipping 'CGAT/Nubiscan/cnubiscan.c' Cython extension (up-to-date)
cythoning scripts/_rnaseq_bams2bam.pyx to scripts/_rnaseq_bams2bam.c

Error compiling Cython file:
------------------------------------------------------------
...
import collections, array, struct, sys
import CGAT.Experiment as E



def filter( Samfile genome_samfile,
           ^
------------------------------------------------------------

scripts/_rnaseq_bams2bam.pyx:8:12: 'Samfile' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
import CGAT.Experiment as E



def filter( Samfile genome_samfile,
            Samfile output_samfile,
           ^
------------------------------------------------------------

scripts/_rnaseq_bams2bam.pyx:9:12: 'Samfile' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...



def filter( Samfile genome_samfile,
            Samfile output_samfile,
            Samfile output_mismapped,
           ^
------------------------------------------------------------
                                                              ....

**Comment by AndreasHeger** [comment]
Hi Cynthia,

strange, _rnaseq_bams2bam.pyx is not part of my repository?

Best wishes,
Andreas

**Comment by csandorfr** [comment]
Hi Andreas,

I just downloaded and updated again the all cgat pipeline

hg clone http://www.cgat.org/hg/cgat/ cgat

(cgat-venv)bash-4.1$ hg pull
pulling from http://www.cgat.org/hg/cgat/
searching for changes
no changes found
(cgat-venv)bash-4.1$ hg update
0 files updated, 0 files merged, 0 files removed, 0 files unresolved


ls -lt ./*pyx
-rw-r--r--. 1 cynthias cppgroup 10723 Feb  5 09:58 ./_rnaseq_bams2bam.pyx
-rw-r--r--. 1 cynthias cppgroup 11743 Feb  5 09:58 ./_gtf2table.pyx
-rw-r--r--. 1 cynthias cppgroup  3644 Feb  5 09:58 ./_bam2stats.pyx
-rw-r--r--. 1 cynthias cppgroup 12372 Feb  5 09:58 ./_bam2peakshape.pyx
-rw-r--r--. 1 cynthias cppgroup 36304 Feb  5 09:58 ./_bam2geneprofile.pyx
-rw-r--r--. 1 cynthias cppgroup  3506 Feb  5 09:58 ./_bam2bed.pyx
-rw-r--r--. 1 cynthias cppgroup  6097 Feb  5 09:58 ./_bam2bam.pyx

Tell me if I did something wrong

**Comment by AndreasHeger** [comment]
Hi Cythnia,

are you not using the github code?

The mercurial repository is very obsolete.

Best wishes,
Andreas

**Comment by csandorfr** [comment]
I updated properly my version of CGAT pipeline with githup.

I reran the pipeline: pipeline_rnaseqdiffexpression.py

python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGATPipelines/pipeline_rnaseqdiffexpression.py --local -v5 make loadEdgeR

I a error when the pipeline run the function: runEdgeR

python /net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py     --method=edger     --tags-tsv-file=gene_counts.dir/genesetexons.gene_counts.tsv.gz     --design-tsv-file=design.tsv     --output-filename-pattern=edger.dir/design_vs_genesetexons.gene_counts_     --outfile=edger.dir/design_vs_genesetexons.gene_counts.tsv.gz     --fdr=0.100000     --filter-min-counts-per-row=1     --filter-min-counts-per-sample=10     --filter-percentile-rowsums=20     > edger.dir/design_vs_genesetexons.gene_counts.tsv.gz.log

Traceback (most recent call last):
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 402, in <module>
    sys.exit(main(sys.argv))
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/scripts/runExpression.py", line 328, in main
    dispersion=options.edger_dispersion)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/cgat/CGAT/Expression.py", line 890, in runEdgeR
    R('''countsTable = estimateGLMCommonDisp(countsTable, design)''')
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/net/isi-scratch/cynthia/CGAT-DEPS/virtualenv-1.11.6/cgat-venv/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in solve.default(R, t(beta)) : 
  system is computationally singular: reciprocal condition number = 4.77764e-17


My input file are:

 zcat gene_counts.dir/genesetexons.gene_counts.tsv.gz | head
gene_id THplus-AH016-R1.star    THplus-JR036-R1.star    THplus-MK002-R1.star    THplus-MK144-R1.star    THplus-NHDF1-R1.star   THplus-OX119-R1.star
ENSG00000223972 0       0       0       0       0       0
ENSG00000227232 34      26      34      16      7       12
ENSG00000243485 0       0       0       0       0       0
ENSG00000237613 0       0       0       0       0       0
ENSG00000268020 0       0       0       0       0       0
ENSG00000240361 6       0       0       0       0       0
ENSG00000186092 0       0       0       0       0       0
ENSG00000238009 0       0       0       11      0       0
ENSG00000239945 0       0       0       1       0       0

head design.tsv 
track   include group   pair
THplus-NHDF1-R1.star    1       Ctr     1
THplus-OX119-R1.star    1       Ctr     1
THplus-AH016-R1.star    1       Ctr     1
THplus-JR036-R1.star    1       Case    2
THplus-MK144-R1.star    1       Case    2
THplus-MK002-R1.star    1       Case    2

**Comment by csandorfr** [comment]
I updated my version of edgeR it works
