### ISSUE TITLE
bam2geneprofile 'RangeCounterBAMBaseAccuracy instance has no attribute 'getTotal''

### ISSUE THREAD

**Issue by osvaldocnio** [CGATOxford/cgat#195]
hi there!

I am just doing my first trials with bam2geneprofile and I am facing a problem that I cannot solve. I would like to show you, please, what the program returns, maybe you have an explanation for that.

The command I've run is:

cgat bam2geneprofile -b SCR_Pol_II_Total_sorted_without_DUP.bam -c SCR_Input_10_sorted_without_DUP.bam --gtf-file=gencode.vM5.annotation.gtf --method=geneprofilewithintrons --output-filename-pattern=prueba2 --extension-upstream=500 --resolution-upstream=500 --extension-downstream=500 --resolution-downstream=500

and it produced the following output:

......
# timeit_name                             : all
# transcript_normalization                : None
Traceback (most recent call last):
  File "/opt/CGAT/conda-install/envs/cgat-scripts/bin/cgat", line 6, in <module>
    sys.exit(main())
  File "/opt/CGAT/conda-install/envs/cgat-scripts/lib/python2.7/site-packages/CGATScripts/cgat.py", line 129, in main
    module.main(sys.argv)
  File "/opt/CGAT/conda-install/envs/cgat-scripts/lib/python2.7/site-packages/CGATScripts/bam2geneprofile.py", line 670, in main
    control_factor=options.control_factor)
  File "ipts/_bam2geneprofile.pyx", line 343, in CGAT._bam2geneprofile.RangeCounterBAMBaseAccuracy.__init__ (scripts/_bam2geneprofile.c:7871)
  File "ipts/_bam2geneprofile.pyx", line 108, in CGAT._bam2geneprofile.RangeCounterBAM.__init__ (scripts/_bam2geneprofile.c:4635)
  File "ipts/_bam2geneprofile.pyx", line 33, in CGAT._bam2geneprofile.RangeCounter.__init__ (scripts/_bam2geneprofile.c:2973)
AttributeError: RangeCounterBAMBaseAccuracy instance has no attribute 'getTotal'
(cgat-scripts)

Surprisingly, it works fine if I don't include the control file, but I must include both as I would like to have both signals drawn in the output image.

Do you now what could be causing the problem?

**Comment by IanSudbery** [comment]
We also saw this problem. PR incoming....

**Comment by AndreasHeger** [comment]
Thanks, how far are you, I just completed it.

**Comment by AndreasHeger** [comment]
Thanks. I will come with a more complete match for the other RangeCounters.
