### ISSUE TITLE
Installation fails on Mac OS 10.10

### ISSUE THREAD

**Issue by bede** [CGATOxford/cgat#203]
I can't install cgat on my one-month-old Mac OS 10.10 installation. I've followed [OS X install instructions](https://www.cgat.org/downloads/public/cgat/documentation/CGATInstallationOSX.html) to the letter, among other things. I use Homebrew anyway, and the only thing which springs to mind as being a cause is the recent version of pip I'm using (7.1.0)  

Whatever I try throws egg-related errors.

```
pip install -r requires.txt
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.1 in ./cgat-python/lib/python3.4/site-packages (from -r requires.txt (line 1))
Collecting pyparsing>=1.5.7 (from -r requires.txt (line 2))
  Using cached pyparsing-2.0.3-py2.py3-none-any.whl
Collecting cython>=0.19 (from -r requires.txt (line 3))
  Using cached Cython-0.22.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.7 (from -r requires.txt (line 4))
  Using cached numpy-1.9.2-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting MySQL-python>1.2.3 (from -r requires.txt (line 5))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/t5/jtr0_yvj5kx2p6_5t_krksw40000gn/T/pip-build-8f1nnb0j/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/t5/jtr0_yvj5kx2p6_5t_krksw40000gn/T/pip-build-8f1nnb0j/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t5/jtr0_yvj5kx2p6_5t_krksw40000gn/T/pip-build-8f1nnb0j/MySQL-python
```

**Comment by AndreasHeger** [comment]
Thanks. This seems to be a problem with installing the MySQL-python module.
Can you try this independently?
```
pip install MySQL-python
```

**Comment by AndreasHeger** [comment]
Closing for now.

**Comment by bede** [comment]
Hi Andreas, I'm sorry for the delay. Yeah I'm still getting the issue with `MySQL-python`.
Have you seen this before?

```
(cgat) l-umobcdja2:cgat Bede$ pip install MySQL-python
Collecting MySQL-python
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/t5/jtr0_yvj5kx2p6_5t_krksw40000gn/T/pip-build-2q8vu9qg/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/t5/jtr0_yvj5kx2p6_5t_krksw40000gn/T/pip-build-2q8vu9qg/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t5/jtr0_yvj5kx2p6_5t_krksw40000gn/T/pip-build-2q8vu9qg/MySQL-python
```
