### ISSUE TITLE
dump MemoryError on R version 3.2.2 (2015-08-14) -- "Fire Safety"

### ISSUE THREAD

**Issue by jaime11** [CGATOxford/cgat#220]
Hello,

Running on LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	Scientific
Description:	Scientific Linux release 6.5 (Carbon)
Release:	6.5
Codename:	Carbon

10GB RAM machine.

I get the following error whether executing 
*python setup.py develop*
or 
*python setup.py develop --multi-version*

         
WARNING: depency check for bedtools(bedtools) failed, error 127
running develop
running egg_info
writing requirements to CGAT.egg-info/requires.txt
writing CGAT.egg-info/PKG-INFO
writing top-level names to CGAT.egg-info/top_level.txt
writing dependency_links to CGAT.egg-info/dependency_links.txt
writing entry points to CGAT.egg-info/entry_points.txt
reading manifest file 'CGAT.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'CGAT.egg-info/SOURCES.txt'
running build_ext
skipping 'CGAT/Components/Components.cpp' Cython extension (up-to-date)
skipping 'CGAT/NCL/cnestedlist.c' Cython extension (up-to-date)
skipping 'CGAT/Timeseries/cmetrics.c' Cython extension (up-to-date)
skipping 'scripts/_bam2bam.c' Cython extension (up-to-date)
skipping 'scripts/_bam2bed.c' Cython extension (up-to-date)
skipping 'scripts/_bam2geneprofile.c' Cython extension (up-to-date)
skipping 'scripts/_bam2peakshape.c' Cython extension (up-to-date)
skipping 'scripts/_bam2stats.c' Cython extension (up-to-date)
skipping 'scripts/_bams2bam.c' Cython extension (up-to-date)
skipping 'scripts/_gtf2table.c' Cython extension (up-to-date)
Creating /home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/CGAT.egg-link (link to .)
Adding CGAT 0.2.4 to easy-install.pth file
Installing cgat script to /home/mbp15ja/.conda/envs/mbp15ja/bin

Installed /home/mbp15ja/dev/cgat
Processing dependencies for CGAT==0.2.4
Searching for rpy2>=2.6
Reading https://pypi.python.org/simple/rpy2/
Best match: rpy2 2.7.0
Downloading https://pypi.python.org/packages/source/r/rpy2/rpy2-2.7.0.tar.gz#md5=afd9ea81a03640b60240b7d53518e652
Processing rpy2-2.7.0.tar.gz
Writing /tmp/easy_install-y1n_DW/rpy2-2.7.0/setup.cfg
Running rpy2-2.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y1n_DW/rpy2-2.7.0/egg-dist-tmp-NPWQ6_
R version 3.2.2 (2015-08-14) -- "Fire Safety"
/usr/local/packages6/R/3.2.2/lib64/R/bin/R CMD config --ldflags
/usr/local/packages6/R/3.2.2/lib64/R/bin/R CMD config --cppflags

    Compilation parameters for rpy2's C components:
        include_dirs    = ['/usr/local/packages6/R/3.2.2/lib64/R/include']
        library_dirs    = ['/usr/local/packages6/R/3.2.2/lib64/R/lib']
        libraries       = ['R', 'rt', 'dl', 'm']
        extra_link_args = ['-Wl,--export-dynamic', '-fopenmp']
    
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Traceback (most recent call last):
  File "setup.py", line 302, in <module>
    test_suite="tests",
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/develop.py", line 32, in run
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/develop.py", line 132, in install_for_development
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/easy_install.py", line 718, in process_distribution
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve
    
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match
    
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain
    
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/easy_install.py", line 638, in easy_install
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/easy_install.py", line 668, in install_item
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/easy_install.py", line 851, in install_eggs
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/easy_install.py", line 1079, in build_and_install
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/command/easy_install.py", line 1065, in run_setup
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 240, in run_setup
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 193, in setup_context
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 152, in save_modules
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 126, in __exit__
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
  File "/home/mbp15ja/.conda/envs/mbp15ja/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/setuptools/sandbox.py", line 110, in dump
MemoryError

Tried uninstalling r: 3.1.2-0 and installing rpy2:
*conda uninstall r*
*conda install rpy2*

Still get the error.

Thank you.

**Comment by sebastian-luna-valero** [comment]
Hi,

It seems that setup.py is using your locally installed R:
```
R version 3.2.2 (2015-08-14) -- "Fire Safety"
/usr/local/packages6/R/3.2.2/lib64/R/bin/R CMD config --ldflags
/usr/local/packages6/R/3.2.2/lib64/R/bin/R CMD config --cppflags
```

instead of the R provided with Conda (the one used to install rpy2).

So there seems to be a conflict. Could you please make sure that you enable your conda environment before `python setup.py develop`

Best regards,
Sebastian.

**Comment by jaime11** [comment]
Hello,

Thank you for the help.

*conda uninstall rpy2*

and

*conda install rpy2*

Still get the same error.

Thanks again.

**Comment by sebastian-luna-valero** [comment]
Hi,

Can you please try to re-install `cgat-devel` following these steps?
```
cd /path/to/working/folder
wget https://raw.githubusercontent.com/CGATOxford/cgat/master/install-CGAT-tools.sh
bash install-CGAT-tools.sh --cgat-devel --location /absolute/path/to/cgat/installation
source /absolute/path/to/cgat/installation/conda-install/bin/activate cgat-devel
```

Please note the **conda-install/bin/activate** part when doing `source`.

Now you should be able to use the command-line tool, by typing:
```
cgat --help
```

I hope it helps.

Best regards,
Sebastian.

**Comment by AndreasHeger** [comment]
Seems to be resolved, closing for now. Please reopen if necessay.
