### ISSUE TITLE
fasta2kmercontent proportions gives division by zero

### ISSUE THREAD

**Issue by osuchanglab** [CGATOxford/cgat#285]
When I run the fasta2kmercontent script with the `--output-proportion` option, I sometimes get a division by zero error. For example, when I run:

`cat ../references/*.fna | cgat fasta2kmercontent --kmer-size 4 --output-proportion`

I get the error message:

`Traceback (most recent call last):
  File "/usr/local/bin/cgat", line 9, in <module>
    load_entry_point('CGAT==0.2.5', 'console_scripts', 'cgat')()
  File "/usr/local/lib/python2.7/site-packages/CGATScripts/cgat.py", line 129, in main
    module.main(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/CGATScripts/fasta2kmercontent.py", line 177, in main
    [row] + [str(float(result[header][tuple(row)]) / totals[header]) for header in headers]) + "\n")
ZeroDivisionError: float division by zero`

This typically occurs when some of the input sequences are relatively short and do not have some of the kmers represented.

When I run the script with the same input files but without the proportions option, it runs successfully, however I would like to compare proportions in my analyses. Thanks!

**Comment by osuchanglab** [comment]
Solved it, the problem was that some of the the input fasta sequences were lowercase text ("atcg", etc). Changing these sequences to all uppercase allowed the code to run correctly. This can be accounted for in the fasta2kmercontent script by either converting the input sequence to uppercase (python's `string.upper()`) or define groups for the nucleotide characters ("Aa", "Cc", etc)
