### ISSUE TITLE
extract_stats: error: no such option: --database-port

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/cgat#331]
Hi @MikeDMorgan 

When I test `pipeline_scrnaseqqc` I get the following error:
```
extract_stats: error: no such option: --database-port
                                                    
                                                    cgat extract_stats     --log=stats.dir/picard_stats.tsv.log     --task=extract_table     --database-port=3306     --database-backend=sqlite     --database-hostname=     --database-username=     --database=reference.dir/csvdb     --table-name=picard_stats_alignment_summary_metrics     > stats.dir/picard_stats.tsv
                                                    -----------------------------------------)' raised in ...
                                                       Task = def getPicardAlignStats(...):
                                                       Job  = [None -> stats.dir/picard_stats.tsv]
```

Could you please have a look?

Best regards,
Sebastian

**Comment by MikeDMorgan** [comment]
Crap, sorry, I pushed the TimeSeries.py bug fix on the wrong branch.  I'll make a PR to fix this.

**Comment by sebastian-luna-valero** [comment]
Thanks @MikeDMorgan !

**Comment by sebastian-luna-valero** [comment]
Many thanks @MikeDMorgan !

The fix is running fine on our standard software setup. However, when I create a conda environment to run `pipeline_testing`, I get:
```
                                                    ValueError: Setting mangle_dupe_cols=False is not supported yet
                                                    
                                                    cgat extract_stats     --task=clean_table     --log=stats.dir/QC_measures.clean.log     stats.dir/QC_measures.stats     > stats.dir/QC_measures.clean
                                                    -----------------------------------------)' raised in ...
                                                       Task = def cleanQcTable(...):
                                                       Job  = [stats.dir/QC_measures.stats -> stats.dir/QC_measures.clean]
```
Please note that the conda environment is not in production yet, so feel free to close this issue if the error is not important.

**Comment by MikeDMorgan** [comment]
Is that the full traceback @sebastian-luna-valero?  It looks like the error might be in pandas perhaps?

**Comment by sebastian-luna-valero** [comment]
Hi @MikeDMorgan 

You're absolutely right. Here is the full traceback:
```
                                                    Exception #1
                                                      'exceptions.OSError(---------------------------------------
                                                    Child was terminated by signal 1: 
                                                    The stderr was: 
                                                    Traceback (most recent call last):
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/bin/cgat", line 11, in <module>
                                                        load_entry_point('CGAT', 'console_scripts', 'cgat')()
                                                      File "/ifs/devel/sebastian/code-py2-2017-05-18/cgat/CGAT/cgat.py", line 129, in main
                                                        module.main(sys.argv)
                                                      File "/ifs/devel/sebastian/code-py2-2017-05-18/cgat/CGAT/scripts/extract_stats.py", line 276, in main
                                                        out_df = cleanStatsTable(infile)
                                                      File "/ifs/devel/sebastian/code-py2-2017-05-18/cgat/CGAT/scripts/extract_stats.py", line 100, in cleanStatsTable
                                                        index_col=None, mangle_dupe_cols=False)
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/lib/python2.7/site-packages/pandas/io/parsers.py", line 655, in parser_f
                                                        return _read(filepath_or_buffer, kwds)
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/lib/python2.7/site-packages/pandas/io/parsers.py", line 405, in _read
                                                        parser = TextFileReader(filepath_or_buffer, **kwds)
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/lib/python2.7/site-packages/pandas/io/parsers.py", line 751, in __init__
                                                        options = self._get_options_with_defaults(engine)
                                                      File "/ifs/devel/sebastian/py2-2017-05-18/lib/python2.7/site-packages/pandas/io/parsers.py", line 777, in _get_options_with_defaults
                                                        raise ValueError('Setting mangle_dupe_cols=False is '
                                                    ValueError: Setting mangle_dupe_cols=False is not supported yet
                                                    
                                                    cgat extract_stats     --task=clean_table     --log=stats.dir/QC_measures.clean.log     stats.dir/QC_measures.stats     > stats.dir/QC_measures.clean
                                                    -----------------------------------------)' raised in ...
                                                       Task = def cleanQcTable(...):
                                                       Job  = [stats.dir/QC_measures.stats -> stats.dir/QC_measures.clean]
```

Sorry for not including that earlier and please let me know your thoughts.

Best regards,
Sebastian

**Comment by MikeDMorgan** [comment]
I guess there is a difference in pandas versions between the CGAT system and the conda env?  This is present in pandas 0.17.1.

**Comment by sebastian-luna-valero** [comment]
Indeed, in the conda env I have pandas 0.20.1

**Comment by MikeDMorgan** [comment]
OK, then it doesn't make sense!  It's documented in 0.20.1 and 0.17.1 with the same type and default.

**Comment by sebastian-luna-valero** [comment]
Just in case it is helpful: It's not only pandas that is running an updated version in the conda env, actually that will be the case for most of the dependencies.

**Comment by MikeDMorgan** [comment]
The function arg (mangle_dupe_cols) from read_table() that's causing the error is in all versions since at least 0.15.0, so the error really doesn't make sense:
http://pandas.pydata.org/pandas-docs/version/0.15.0/generated/pandas.read_table.html

**Comment by sebastian-luna-valero** [comment]
Thanks @MikeDMorgan 

Will close the issue for now.
