### ISSUE TITLE
TypeError: '<' not supported between instances of 'Bed' and 'Bed' on merging with bed2bed

### ISSUE THREAD

**Issue by blaiseli** [CGATOxford/cgat#347]
The following file causes a failure of `bed2bed --method=merge --merge-by-name`:
```
$ cat /tmp/bug.bed 
III	13782586	13782934	"WBGene00007066"	.	+
III	13782586	13783459	"WBGene00007066"	.	+
III	13783360	13783459	"WBGene00007066"	.	+
IV	694	1065	"WBGene00021406"	.	+
```

```
$ cgat bed2bed --method=merge --merge-by-name -I /tmp/bug.bed 
# output generated by bed2bed --method=merge --merge-by-name -I /tmp/bug.bed
# job started at Thu Aug 10 18:20:32 2017 on naples -- 6ea718c4-139d-4f30-911c-0d70f737f3fd
# pid: 25330, system: Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64
# bam_file                                : None
# bin_edges                               : None
# binning_method                          : equal-bases
# extend_distance                         : 1000
# genome_file                             : None
# loglevel                                : 1
# merge_by_name                           : True
# merge_distance                          : 0
# merge_min_intervals                     : 1
# methods                                 : ['merge']
# names                                   : None
# num_bins                                : 5
# offset                                  : 10000
# random_seed                             : None
# remove_inconsistent_names               : False
# resolve_blocks                          : False
# short_help                              : None
# stderr                                  : <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>
# stdin                                   : <_io.TextIOWrapper name='/tmp/bug.bed' mode='r' encoding='UTF-8'>
# stdlog                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stdout                                  : <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
# stranded                                : None
# test                                    : None
# timeit_file                             : None
# timeit_header                           : None
# timeit_name                             : all
III	13782586	13782934	"WBGene00007066"	.	+
Traceback (most recent call last):
  File "/home/bli/.local/bin/cgat", line 11, in <module>
    load_entry_point('CGAT==0.3.0', 'console_scripts', 'cgat')()
  File "/home/bli/.local/lib/python3.6/site-packages/CGAT/cgat.py", line 129, in main
    module.main(sys.argv)
  File "/home/bli/.local/lib/python3.6/site-packages/CGAT/scripts/bed2bed.py", line 624, in main
    for bed in processor:
  File "/home/bli/.local/lib/python3.6/site-packages/CGAT/scripts/bed2bed.py", line 250, in merge
    for to_join in iterate_chunks(iterator):
  File "/home/bli/.local/lib/python3.6/site-packages/CGAT/scripts/bed2bed.py", line 225, in iterate_chunks
    if sorted(to_join[s]):
TypeError: '<' not supported between instances of 'Bed' and 'Bed'
```
`head -3 /tmp/bug.bed | cgat bed2bed --method=merge --merge-by-name` don't cause the error.

`tail -3 /tmp/bug.bed | cgat bed2bed --method=merge --merge-by-name` neither, but the result is not what I expected:

```
III	13782586	13783459	"WBGene00007066"	.	+
III	13783360	13783459	"WBGene00007066"	.	+
IV	694	1065	"WBGene00021406"	.	+
```

There are two successive lines with the same name. I expected them to be merged.

Is this file not conforming to the expected format?

**Comment by IanSudbery** [comment]
I can see the problem with duplicated entries:

`last_name[strand]` @ line 232 will always be empty on the first comparison, thus the first and second lines will always appear to have different names. I havn't figured if this applies to the first comparison on each strand. 

PR incoming.

**Comment by IanSudbery** [comment]
I don't can't reproduce the `TypeError`. I am however, running in Py2, perhaps someone in py3 could have a go?

**Comment by KatyBrown** [comment]
I think the TypeError is a python 3 problem as I have encountered it in another context in python 3 - I think the error is caused by trying to run the sorted() function on to_join.  I have made a pull request on a bugfix for this but I'd like Andreas to review before I merge.

**Comment by blaiseli** [comment]
@IanSudbery I tried your branch, and I confirm the bed records seem to be fused as expected now. Thanks.
