### ISSUE TITLE
addMLE=TRUE is only for when a beta prior was used

### ISSUE THREAD

**Issue by sebastian-luna-valero** [CGATOxford/cgat#363]
Hi @CGATOxford/contributors,

When running `pipeline_testing.py` I run into the following issue in task `runDESeq2` of `pipeline_rnaseqdiffexpression.py`. 

```
       Task = def runDESeq2(...):
       Job  = [[[featurecounts.dir/transcripts.tsv.gz, featurecounts.dir/genes.tsv.gz], design2.tsv] -> [DEresults.dir/deseq2/featurecounts_2_transcripts_results.tsv, DEresults.dir/deseq2/featurecounts_2_genes_results.tsv], 2]
    
    Traceback (most recent call last):
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/CGATPipelines/CGATPipelines/pipeline_rnaseqdiffexpression.py", line 1165, in runDESeq2
        P.run()
      File "/ifs/mirror/jenkins/PipelineRegressionTests/CGATPipelines/CGATPipelines/Pipeline/Execution.py", line 548, in run
        ignore_errors=ignore_errors)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/CGATPipelines/CGATPipelines/Pipeline/Cluster.py", line 327, in collectSingleJobFromCluster
        "".join(stderr), statement))
    OSError: ---------------------------------------
    Child was terminated by signal 1: 
    The stderr was: 
    /ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/ggplot/components/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
      from pandas.lib import Timestamp
    /ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
      from pandas.core import datetools
    /ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/rpy2/robjects/functions.py:106: UserWarning: Error in results(dds, addMLE = TRUE) : 
      addMLE=TRUE is only for when a beta prior was used.
    otherwise, the log2 fold changes are already MLE
    
      res = super(Function, self).__call__(*new_args, **new_kwargs)
    Traceback (most recent call last):
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/bin/cgat", line 11, in <module>
        load_entry_point('CGAT==0.3.0', 'console_scripts', 'cgat')()
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/CGAT-0.3.0-py3.6-linux-x86_64.egg/CGAT/cgat.py", line 132, in main
        module.main(sys.argv)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/CGAT-0.3.0-py3.6-linux-x86_64.egg/CGAT/scripts/counts2table.py", line 490, in main
        R=RH)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/CGAT-0.3.0-py3.6-linux-x86_64.egg/CGAT/Expression.py", line 968, in run
        ''' % locals())
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 321, in __call__
        res = self.eval(p)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 178, in __call__
        return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
      File "/ifs/mirror/jenkins/PipelineRegressionTests/conda-install/envs/jenkins-env/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 106, in __call__
        res = super(Function, self).__call__(*new_args, **new_kwargs)
    rpy2.rinterface.RRuntimeError: Error in results(dds, addMLE = TRUE) : 
      addMLE=TRUE is only for when a beta prior was used.
    otherwise, the log2 fold changes are already MLE
    
    
    cgat counts2table     --tag-tsv-file=featurecounts.dir/transcripts.tsv.gz     --design-tsv-file=design2.tsv     --method=deseq2     --de-test=wald     --output-filename-pattern=DEresults.dir/deseq2/featurecounts_2_transcripts_results     --model=~group     --contrast=group     --reference-group=Brain1     --fdr=0.05     --log=DEresults.dir/deseq2/featurecounts_2_transcripts_results.log     -v 0     > DEresults.dir/deseq2/featurecounts_2_transcripts_results.tsv
```

Specifically, the error is:
```
Error in results(dds, addMLE = TRUE) : 
      addMLE=TRUE is only for when a beta prior was used.
    otherwise, the log2 fold changes are already MLE
```

It points to class `DEExperiment_DESeq2` in `Expression.py`:
https://github.com/CGATOxford/cgat/blob/master/CGAT/Expression.py#L951

I am using `DESeq2` version 1.16.1. 

Should we:
* update `Expression.py`? if so, how? I found [this thread](https://support.bioconductor.org/p/99102/) which may help but I don't feel comfortable doing the change.
* downgrade `DESeq2`? if so, which version do you recommend?

Best regards,
Sebastian

**Comment by Acribbs** [comment]
Seems that the beta prior defaults to FALSE now for versions of DESeq2 > 1.16. Looks like there is a lfcShrink() function that should be implemented if using the new version of the code. 

This is taken from the manual:
```
In version 1.16 (November 2016), the log2 fold change shrinkage is no longer default for the DESeq and nbinomWaldTest functions, by setting the defaults of these to betaPrior=FALSE, and by introducing a separate function lfcShrink, which performs log2 fold change shrinkage for visualization and ranking of genes. While for the majority of bulk RNA-seq experiments, the LFC shrinkage did not affect statistical testing, DESeq2 has become used as an inference engine by a wider community, and certain sequencing datasets show better performance with the testing separated from the use of the LFC prior.
```

Therefore, we have two options:
- Keep the code as it is and revert to a version of DESeq2 < 1.16
- or I can implement lfcShrink()

I didn't  have a strong preference for either because the underlying model won't change, however  it may be best to upgrade to newest version of 1.18 because there is implementation for two different types of shrinkage estimators. Therefore, I dont mind making the changes.

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs 

Please note that we are using `R 3.4.1` and therefore `Bioconductor 3.5`, whereas `DESeq2 1.18` is available for `R 3.4.2` and `Bioconductor 3.6` (just released). 

For this release of the CGAT code, I would like to stick to `Bioconductor 3.5`. If you could make the changes for `DESeq2 1.16` in a pull request, that would be brilliant!

Best regards,
Sebastian

**Comment by Acribbs** [comment]
ok no worries,

I will implement the changes tomorrow  (Hopefully) and then close the issue when complete.

**Comment by sebastian-luna-valero** [comment]
@Acribbs thanks for working on this on branch `AC-deseq`.

I am now testing the code and I get the following errors:
```
                                                      Task = def runDESeq2(...):
                                                      Job  = [[[featurecounts.dir/transcripts.tsv.gz, featurecounts.dir/genes.tsv.gz], design2.tsv] -> [DEresults.dir/deseq2/featurecounts_2_transcripts_results.tsv, DEresults.dir/deseq2/fe
aturecounts_2_genes_results.tsv], 2]
                                                   
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
                                                       register_cleanup, touch_files_only)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
                                                       ret_val = user_defined_work_func(*params)
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/pipeline_rnaseqdiffexpression.py", line 1165, in runDESeq2
                                                       P.run()
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/Pipeline/Execution.py", line 548, in run
                                                       ignore_errors=ignore_errors)
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/Pipeline/Cluster.py", line 327, in collectSingleJobFromCluster
                                                       "".join(stderr), statement))
                                                   OSError: ---------------------------------------
                                                   Child was terminated by signal 1: 
                                                   The stderr was: 
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ggplot/components/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
                                                     from pandas.lib import Timestamp
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
                                                     from pandas.core import datetools
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in plotMA(res, alpha = 0.05) : 
                                                     Error from the generic function 'plotMA' defined in package 'BiocGenerics': no S4 method definition for argument 'res' of class 'numeric' was found. Did you perhaps mean calling the function 'plotMA' from another package, e.g. 'limma'? In that case, please use the syntax 'limma::plotMA'.
                                                   
                                                     warnings.warn(x, RRuntimeWarning)
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/bin/cgat", line 11, in <module>
                                                       load_entry_point('CGAT', 'console_scripts', 'cgat')()
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/cgat.py", line 132, in main
                                                       module.main(sys.argv)
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/scripts/counts2table.py", line 490, in main
                                                       R=RH)
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/Expression.py", line 969, in run
                                                       ''' % locals())
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 363, in __call__
                                                       res = self.eval(p)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 178, in __call__
                                                       return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 106, in __call__
                                                       res = super(Function, self).__call__(*new_args, **new_kwargs)
                                                   rpy2.rinterface.RRuntimeError: Error in plotMA(res, alpha = 0.05) : 
                                                     Error from the generic function 'plotMA' defined in package 'BiocGenerics': no S4 method definition for argument 'res' of class 'numeric' was found. Did you perhaps mean calling the function 'plotMA' from another package, e.g. 'limma'? In that case, please use the syntax 'limma::plotMA'.
                                                   
                                                   
                                                   cgat counts2table     --tag-tsv-file=featurecounts.dir/transcripts.tsv.gz     --design-tsv-file=design2.tsv     --method=deseq2     --de-test=wald     --output-filename-pattern=DEresults.dir/deseq2/featurecounts_2_transcripts_results     --model=~group     --contrast=group     --reference-group=Brain1     --fdr=0.05     --log=DEresults.dir/deseq2/featurecounts_2_transcripts_results.log     -v 0     > DEresults.dir/deseq2/featurecounts_2_transcripts_results.tsv
```

Could you please let me know your opinion?
Best regards,
Sebastian

**Comment by Acribbs** [comment]
@sebastian-luna-valero  Did the last change fix this?

**Comment by sebastian-luna-valero** [comment]
@Acribbs it didn't:
```
Task = def runDESeq2(...):
                                                      Job  = [[[featurecounts.dir/transcripts.tsv.gz, featurecounts.dir/genes.tsv.gz], design2.tsv] -> [DEresults.dir/deseq2/featurecounts_2_transcripts_results.tsv, DEresults.dir/deseq2/fe
aturecounts_2_genes_results.tsv], 2]
                                                   
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
                                                       register_cleanup, touch_files_only)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
                                                       ret_val = user_defined_work_func(*params)
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/pipeline_rnaseqdiffexpression.py", line 1165, in runDESeq2
                                                       P.run()
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/Pipeline/Execution.py", line 548, in run
                                                       ignore_errors=ignore_errors)
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/Pipeline/Cluster.py", line 327, in collectSingleJobFromCluster
                                                       "".join(stderr), statement))
                                                   OSError: ---------------------------------------
                                                   Child was terminated by signal 1: 
                                                   The stderr was: 
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ggplot/components/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
                                                     from pandas.lib import Timestamp
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
                                                     from pandas.core import datetools
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in DESeq2::plotMA(res, alpha = 0.05) : 
                                                     Error from the generic function 'plotMA' defined in package 'BiocGenerics': no S4 method definition for argument 'res' of class 'numeric' was found. Did you perhaps mean calling the function 'plotMA' from another package, e.g. 'limma'? In that case, please use the syntax 'limma::plotMA'.
                                                   
                                                     warnings.warn(x, RRuntimeWarning)
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/bin/cgat", line 11, in <module>
                                                       load_entry_point('CGAT', 'console_scripts', 'cgat')()
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/cgat.py", line 132, in main
                                                       module.main(sys.argv)
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/scripts/counts2table.py", line 490, in main
                                                       R=RH)
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/Expression.py", line 969, in run
                                                       ''' % locals())
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 363, in __call__
                                                       res = self.eval(p)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 178, in __call__
                                                       return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/rpy2/robjects/functions.py", line 106, in __call__
                                                       res = super(Function, self).__call__(*new_args, **new_kwargs)
                                                   rpy2.rinterface.RRuntimeError: Error in DESeq2::plotMA(res, alpha = 0.05) : 
                                                     Error from the generic function 'plotMA' defined in package 'BiocGenerics': no S4 method definition for argument 'res' of class 'numeric' was found. Did you perhaps mean calling the function 'plotMA' from another package, e.g. 'limma'? In that case, please use the syntax 'limma::plotMA'.
                                                   
                                                   
                                                   cgat counts2table     --tag-tsv-file=featurecounts.dir/transcripts.tsv.gz     --design-tsv-file=design2.tsv     --method=deseq2     --de-test=wald     --output-filename-pattern=DEresults.dir/deseq2/featurecounts_2_transcripts_results     --model=~group     --contrast=group     --reference-group=Brain1     --fdr=0.05     --log=DEresults.dir/deseq2/featurecounts_2_transcripts_results.log     -v 0     > DEresults.dir/deseq2/featurecounts_2_transcripts_results.tsv
```

Although it seems to be picking up the change now:
```
rpy2.rinterface.RRuntimeError: Error in DESeq2::plotMA(res, alpha = 0.05) : 
                                                     Error from the generic function 'plotMA' defined in package 'BiocGenerics': no S4 method definition for argument 'res' of class 'numeric' was found. Did you perhaps mean calling the function 'plotMA' from another package, e.g. 'limma'? In that case, please use the syntax 'limma::plotMA'.
```
Any ideas?
Best regards,
Sebastian

**Comment by Acribbs** [comment]
Hmm, im running out of ideas because the plotMA function should work with the changed we implimented. Ah actually, I think the plotMA does not take the alpha=0.05, this seems to have moved to the results() function. When im finished my meetings I will make another pull request.

**Comment by Acribbs** [comment]
Ah! plotMA now works directly on the ads object, the changes I made are only half the solution. please see: https://support.bioconductor.org/p/58342/. I will add to the pull request soon

**Comment by sebastian-luna-valero** [comment]
Ok, so new issue now. This time related to pandas:
```
                                                      Task = def runDESeq2(...):
                                                      Job  = [[[featurecounts.dir/transcripts.tsv.gz, featurecounts.dir/genes.tsv.gz], design1.tsv] -> [DEresults.dir/deseq2/featurecounts_1_transcripts_results.tsv, DEresults.dir/deseq2/featurecounts_1_genes_results.tsv], 1]
                                                   
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
                                                       register_cleanup, touch_files_only)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
                                                       ret_val = user_defined_work_func(*params)
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/pipeline_rnaseqdiffexpression.py", line 1165, in runDESeq2
                                                       P.run()
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/Pipeline/Execution.py", line 548, in run
                                                       ignore_errors=ignore_errors)
                                                     File "/ifs/devel/sebastian/py36-v1/CGATPipelines/CGATPipelines/Pipeline/Cluster.py", line 327, in collectSingleJobFromCluster
                                                       "".join(stderr), statement))
                                                   OSError: ---------------------------------------
                                                   Child was terminated by signal 1: 
                                                   The stderr was: 
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/ggplot/components/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
                                                     from pandas.lib import Timestamp
                                                   /ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
                                                     from pandas.core import datetools
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2442, in get_loc
                                                       return self._engine.get_loc(key)
                                                     File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
                                                     File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
                                                     File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
                                                     File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
                                                   KeyError: 'baseMean'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/bin/cgat", line 11, in <module>
                                                       load_entry_point('CGAT', 'console_scripts', 'cgat')()
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/cgat.py", line 132, in main
                                                       module.main(sys.argv)
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/scripts/counts2table.py", line 492, in main
                                                       results.getResults(fdr=options.fdr)
                                                     File "/ifs/devel/sebastian/py36-v1/cgat/CGAT/Expression.py", line 1092, in getResults
                                                       df_dict["control_mean"] = self.table['baseMean']
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/pandas/core/frame.py", line 1964, in __getitem__
                                                       return self._getitem_column(key)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
                                                       return self._get_item_cache(key)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
                                                       values = self._data.get(item)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/pandas/core/internals.py", line 3590, in get
                                                       loc = self.items.get_loc(item)
                                                     File "/ifs/devel/sebastian/py36-v1/conda/envs/py36-v1/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
                                                       return self._engine.get_loc(self._maybe_cast_indexer(key))
                                                     File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
                                                     File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
                                                     File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
                                                     File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
                                                   KeyError: 'baseMean'
                                                   
                                                   cgat counts2table     --tag-tsv-file=featurecounts.dir/transcripts.tsv.gz     --design-tsv-file=design1.tsv     --method=deseq2     --de-test=wald     --output-filename-pattern=DEresults.dir/deseq2/featurecounts_1_transcripts_results     --model=~group     --contrast=group     --reference-group=Brain1     --fdr=0.05     --log=DEresults.dir/deseq2/featurecounts_1_transcripts_results.log     -v 0     > DEresults.dir/deseq2/featurecounts_1_transcripts_results.tsv
```
