### ISSUE TITLE
Install error on installation of production version

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#381]
I've just been testing the new installer, and after installing get the following error when I run, for example, `cgat runExpression`:

```python-traceback
Traceback (most recent call last):
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/bin/cgat", line 6, in <module>
    sys.exit(CGAT.cgat.main())
  File "/home/mb1ims/devel/cgat/CGAT/cgat.py", line 126, in main
    module = imp.load_module(command, file, pathname, description)
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mb1ims/devel/cgat/CGAT/scripts/runExpression.py", line 138, in <module>
    from rpy2.robjects import r as R
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 71, in RObjectMixin
    __show = rpy2.rinterface.baseenv.get("show")
LookupError: 'show' not found
```

Running the rpy2 tests shows the source of the problem:

```
(cgat-s) $ python -m rpy2.tests
rpy2 version: 2.8.5
- built against R version: 3-4.1--72865
- running linked to R version: R version 3.3.2 (2016-10-31)
E
======================================================================
ERROR: __main__ (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/tests.py", line 43, in load_tests
    suite_robjects = loader.discover('robjects', pattern, rpy_root)
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/unittest/loader.py", line 290, in discover
    __import__(start_dir)
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/__init__.py", line 19, in <module>
    from rpy2.robjects.robject import RObjectMixin, RObject
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 58, in <module>
    class RObjectMixin(object):
  File "/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/robjects/robject.py", line 71, in RObjectMixin
    __show = rpy2.rinterface.baseenv.get("show")
LookupError: 'show' not found

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

This suggests that rpy2 was build against 3.4.1, but is linked against 3.3.2
However, if I run R from the commandline I get the conda R (3.4.1):

```
(cgat-s) $ which R
/data/mb1ims/cgat_instal_test/conda-install/envs/cgat-s/bin/R
(cgat-s) $ R

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
So the conda R is installed and is being used as default.

R 3.3.2 is the system version of R.  As I'm on a HPC without root access, I have no power to change this. One guess for what is happening is that conda is installing rpy2 before r-base, and thus when rpy2 is installed, the system R is the default?

**Comment by AndreasHeger** [comment]
I think your diagnosis is correct, the issue is that rpy2 at runtime finds the wrong R. I don't think this is and 'order of package' problem. AFAIK, conda will not recompile. It seems that PATHS are a problem.
What does ldd tell you? In my repo, though not updated for a while:
```
  ldd /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/_rinterface.cpython-35m-x86_64-linux-gnu.so 
        linux-vdso.so.1 =>  (0x00007ffe20f89000)
        libR.so => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/libR.so (0x00002b16e0a66000)
        libpcre.so.1 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libpcre.so.1 (0x00002b16e10eb000)
        liblzma.so.5 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../liblzma.so.5 (0x00002b16e132d000)
        libbz2.so.1.0 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libbz2.so.1.0 (0x00002b16e1552000)
        libz.so.1 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libz.so.1 (0x00002b16e1762000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b16e199f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b16e1ba8000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b16e1dac000)
        libiconv.so.2 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libiconv.so.2 (0x00002b16e2030000)
        libicuuc.so.58 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libicuuc.so.58 (0x00002b16e231f000)
        libicui18n.so.58 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libicui18n.so.58 (0x00002b16e271e000)
        libpython3.5m.so.1.0 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libpython3.5m.so.1.0 (0x00002b16e2c1f000)
        libgomp.so.1 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../libgomp.so.1 (0x00002b16e3147000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b16e3356000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b16e3573000)
        libgfortran.so.3 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/../../libgfortran.so.3 (0x00002b16e3908000)
        libRblas.so => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/./libRblas.so (0x00002b16e3c2e000)
        libquadmath.so.0 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/../../libquadmath.so.0 (0x00002b16e3e71000)
        libreadline.so.6 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/../../libreadline.so.6 (0x00002b16e40ad000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003493e00000)
        libicudata.so.58 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../.././libicudata.so.58 (0x00002b16e42f0000)
        libstdc++.so.6 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../.././libstdc++.so.6 (0x00002b16e5df0000)
        libgcc_s.so.1 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../.././libgcc_s.so.1 (0x00002b16e6107000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002b16e631d000)
        libncurses.so.5 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/../.././libncurses.so.5 (0x00002b16e6521000)
        libtinfo.so.5 => /ifs/devel/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.5/site-packages/rpy2/rinterface/../../../../R/lib/../.././libtinfo.so.5 (0x00002b16e6746000)
```

**Comment by AndreasHeger** [comment]
I did a fresh install, but now the linking is wrong as for you:
```
  ldd cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/_rinterface.cpython-36m-x86_64-linux-gnu.so 
        linux-vdso.so.1 =>  (0x00007ffcee3d2000)
        libgfortran.so.3 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libgfortran.so.3 (0x00002b1cdb319000)
        libR.so => /ifs/apps/apps/R-3.3.0/lib64/R/lib/libR.so (0x00002b1cdb63f000)
        libpcre.so.1 => /ifs/apps/system/pcre-8.38/lib/libpcre.so.1 (0x00002b1cdbc5a000)
        liblzma.so.5 => /ifs/apps/system/xz-5.2.2/lib/liblzma.so.5 (0x00002b1cdbec9000)
        libbz2.so.1.0 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libbz2.so.1.0 (0x00002b1cdc0ee000)
        libz.so.1 => /ifs/apps/system/zlib-1.2.8/lib/libz.so.1 (0x00002b1cdc2fe000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b1cdc53a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b1cdc742000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b1cdc946000)
        libiconv.so.2 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libiconv.so.2 (0x00002b1cdcbcb000)
        libicuuc.so.58 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libicuuc.so.58 (0x00002b1cdceba000)
        libicui18n.so.58 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libicui18n.so.58 (0x00002b1cdd2ba000)
        libpython3.6m.so.1.0 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libpython3.6m.so.1.0 (0x00002b1cdd7ba000)
        libgomp.so.1 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../../libgomp.so.1 (0x00002b1cddcf5000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b1cddf19000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b1cde136000)
        libquadmath.so.0 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../.././libquadmath.so.0 (0x00002b1cde4cb000)
        libgcc_s.so.1 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../.././libgcc_s.so.1 (0x00002b1cde6fc000)
        libRblas.so => /ifs/apps/apps/R-3.3.0/lib64/R/lib/libRblas.so (0x00002b1cde90f000)
        libreadline.so.6 => /lib64/libreadline.so.6 (0x00002b1cdeb3a000)
        libpcre.so.0 => /lib64/libpcre.so.0 (0x00002b1cded7d000)
        libbz2.so.1 => /ifs/apps/system/bzip2-1.0.6/lib/libbz2.so.1 (0x00002b1cdefaa000)
        libicuuc.so.42 => /usr/lib64/libicuuc.so.42 (0x00002b1cdf1bb000)
        libicui18n.so.42 => /usr/lib64/libicui18n.so.42 (0x00002b1cdf50d000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003493e00000)
        libicudata.so.58 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../.././libicudata.so.58 (0x00002b1cdf8a4000)
        libstdc++.so.6 => /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/../../../.././libstdc++.so.6 (0x00002b1ce13a4000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002b1ce16df000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00002b1ce18e2000)
        libicudata.so.42 => /usr/lib64/libicudata.so.42 (0x00002b1ce1b04000)
```

**Comment by AndreasHeger** [comment]
and I get same error.

**Comment by AndreasHeger** [comment]
The differences to the previous install (aside from older rpy2) is the origin. The latest install uses rpy2 from conda-forge instead of bioconda.

**Comment by AndreasHeger** [comment]
I can recover this by doing the following:

```
export LD_LIBRARY_PATH=/scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/R/lib:$LD_LIBRARY_PATH
```
I think this is a conda problem or a problem in how rpy2 is built in conda-forge. I will create a pull-request with the work-around.

**Comment by AndreasHeger** [comment]
... scratch that. The paths in rpy2 are set correctly.
My suspicion is that you have an LD_LIBRARY_PATH set? If so, this will be used first. Can you try:
```
export LD_LIBRARY_PATH=
```

**Comment by AndreasHeger** [comment]
This is what the paths are:
```
  patchelf --print-rpath /scratch/andreas/cgat-install/conda-install/envs/cgat-s/lib/python3.6/site-packages/rpy2/rinterface/*.so
$ORIGIN/../../../..:$ORIGIN/../../../../R/lib
```

**Comment by AndreasHeger** [comment]
Good to hear that this is solved.
