### ISSUE TITLE
Testing imports

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/cgat#91]
Hi Guys,

I'm try to merge a branch into the repository, and so I'm try to run all the tests. Do we regularly check that test_import works? Running this produces a rather large number of errors in obscure modules, making it look like this isn't used often. Am I right in assuming this?

Ian
---

**Comment by AndreasHeger** [comment]
Hi Ian,

which bits are failing?

I think it is active. Typically it will fail on cython extensions, you might need to run 

python setup.py develop
python scripts/cgat_rebuild_extensions.py

Best wishes,
Andreas

**Comment by sebastian-luna-valero** [comment]
Hi Ian, Andreas

Yes, test_import.py is active on travis-ci and there are currently 588
tests passing OK in the latest builds.

Best regards,
Sebastian.


2015-01-08 10:45 GMT+00:00 Andreas Heger <notifications@github.com>:

**Comment by IanSudbery** [comment]
I had run rebuild_extensions, but not setup.py develop. 

setup.py develop doesn't complete anymore:

```python-traceback
Processing dependencies for CGAT==0.2.3
Traceback (most recent call last):
  File "setup.py", line 301, in <module>
    test_suite="tests",
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
    self.install_for_development()
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/setuptools/command/develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/ifs/apps/apps/python-2.7.1/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 704, in process_distribution
    % e.args
TypeError: not enough arguments for format string
```

Looking at the import errors again more closely (as I should have done before), they are all the same error:
```
Exception: 'module' object has no attribute 'PileupProxy'
```

I assume this is to do with the new version of pysam?

I also have a lot of pep8 errors in pipelines. Have these been newly added to the style tests, I can't see that the pep8 errors in, say pipeline_transfacmatch.py are new?

Ian
---

**Comment by AndreasHeger** [comment]
@IanSudbery, yes, that might have to do with the new version of pysam. I will need to look at the setuptools error.

The pep8 tests generally all pass, are you working from a recent pull?

**Comment by IanSudbery** [comment]
Hi Andreas,

Okay, so I'd rebased by branch to the current master, but had forgotten to update the master. Ooops.  :}. 
This solves both the style and import fails. Sorry.

All tests now pass.

Ian
